### ISSUE TITLE
Need to be in play area to select avatar.

### ISSUE THREAD

**Issue by caseyyee** [aframevr/a-saturday-night#116]
its very difficult or not possible to choose your avatar.

**Comment by caseyyee** [comment]
Ah I found the issue.  It's due to not being in the stage area.   Probably need some UX that informs the user that they must be int he play area to start.

**Comment by dmarcos** [comment]
We should make the raycaster distance limit a bit more generous

**Comment by caseyyee** [comment]
Thanks!
