### ISSUE TITLE
Can't select the bear avatar

### ISSUE THREAD

**Issue by fernandojsg** [aframevr/a-saturday-night#121]
I can select the rest of the avatars but as soon as I select the bear it just keeps highlighted and it doesn't do anything

**Comment by dmarcos** [comment]
Digging into this I observed this is related to the selected avatar by the default dance (default.json). Changing manually the avatar in the json (avatar3 -> avatar2) makes a different character to break. It seems that the transition from instructions->dancing->selectAvatar conflicts with the selected by the default dance one.
